import { MenuItem, MenuCategory, SectionInfo } from '../types';

export const RESTAURANT_NAME = "SPOONS KERALA RESTAURANT";
export const RESTAURANT_TAGLINE = "Authentic Malabar & Central Travancore Delicacies";
export const MEAL_SHARING_POLICY = "Meals sharing not allowed";

export const SECTIONS: SectionInfo[] = [
  {
    id: 'specials',
    path: '/menu/specials',
    title: 'Spoons Specials & Meals',
    shortTitle: 'Specials & Meals',
    description: 'Spoons Special Kerala Items, Lunch Pothichoru, Tapioca (Kappa), Puttu & Breads',
    categories: ['SPOONS SPECIAL KERALA ITEMS', 'LUNCH', 'KAPPA', 'PUTTU ITEMS', 'KERALA VARIETY'],
    bannerSubtitle: 'Signature banana-leaf wraps, fresh fish & kappa delicacies',
    bgAccent: '#1B432A',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'biriyani',
    path: '/menu/biriyani',
    title: 'Biriyani & Kizhi Specialties',
    shortTitle: 'Biriyani & Kizhi',
    description: 'Kizhi Biriyani steamed in banana leaves, Dum Biriyanis, Butter Biriyanis & Kothu Parottas',
    categories: ['KIZHI BIRIYANI', 'BIRIYANI', 'SPOONS SPECIAL BUTTER BIRIYANI', 'KIZHI POROTTA', 'KOTTHU PAROTTA'],
    bannerSubtitle: 'Aromatic jeerakasala rice, tender spices & banana-leaf sealed flavours',
    bgAccent: '#823214',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'mains',
    path: '/menu/mains',
    title: 'Curries & Traditional Mains',
    shortTitle: 'Curries & Mains',
    description: 'Slow-roasted Chicken, Syrian Christian Beef preparations, Farm Egg Masalas & Veg Curries',
    categories: ['CHICKEN ITEMS', 'BEEF ITEMS', 'EGG ITEMS', 'VEG CURRY'],
    bannerSubtitle: 'Rich coconut gravies, dry pepper roasts & slow-cooked masala pans',
    bgAccent: '#5C220E',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'rice-noodles',
    path: '/menu/rice-noodles',
    title: 'Rice, Noodles & Quick Rolls',
    shortTitle: 'Rice, Noodles & Rolls',
    description: 'Wok-tossed Fried Rice, Schezwan specialties, Hakka Noodles & Savory Rolls',
    categories: ['FRIED RICE', 'NOODLES', 'ROLL ITEMS'],
    bannerSubtitle: 'Crisp vegetables, fragrant long-grain rice, spiced meats and wraps',
    bgAccent: '#265C3B',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1000&q=80',
  },
];

// Helper to determine dietary type
function detectDiet(name: string, category: string): MenuItem['diet'] {
  const lower = (name + ' ' + category).toLowerCase();
  if (lower.includes('fish') || lower.includes('prawn') || lower.includes('crab') || lower.includes('squid') || lower.includes('anchovy') || lower.includes('netholy') || lower.includes('thala')) {
    return 'seafood';
  }
  if (lower.includes('beef') || lower.includes('chicken') || lower.includes('non veg') || lower.includes('non-veg') || lower.includes('65') || lower.includes('al faham') || lower.includes('meat')) {
    return 'non-veg';
  }
  if (lower.includes('egg') || lower.includes('omelette') || lower.includes('boil') || lower.includes('burji')) {
    return 'egg';
  }
  return 'veg';
}

export const MENU_ITEMS: MenuItem[] = [
  // ==========================================
  // SPOONS SPECIAL KERALA ITEMS (Page: specials)
  // ==========================================
  {
    id: 'spec-prawns-roast',
    name: 'Prawns Roast',
    price: 240,
    priceDisplay: '₹240',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Fresh prawns pan-roasted with shallots, crushed ginger, curry leaves and coconut oil',
    isChefSpecial: true,
    isPopular: true,
    spicyLevel: 2,
  },
  {
    id: 'spec-crab-roast',
    name: 'Crab Roast',
    price: 260,
    priceDisplay: '₹260',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Succulent fresh crab tossed in a rich, peppery Kerala spiced onion-tomato masala',
    isChefSpecial: true,
    isPopular: true,
    spicyLevel: 3,
  },
  {
    id: 'spec-squid-roast',
    name: 'Squid Roast',
    price: 230,
    priceDisplay: '₹230',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Tender squid rings slow-braised with freshly ground Tellicherry black pepper and roasted coconut slivers',
    isChefSpecial: true,
    spicyLevel: 2,
  },
  {
    id: 'spec-anchovy-fry',
    name: 'Anchovy (Netholy) Fry',
    price: 160,
    priceDisplay: '₹160',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Crispy fried netholy coated in spicy red chili paste and curry leaf infused coconut oil',
    isPopular: true,
    spicyLevel: 2,
  },
  {
    id: 'spec-fish-mulaku-curry',
    name: 'Fish Mulaku Curry',
    price: 180,
    priceDisplay: '₹180',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Traditional fiery red Travancore fish curry simmered with kudampuli (pot tamarind)',
    isChefSpecial: true,
    spicyLevel: 3,
  },
  {
    id: 'spec-fish-thala-fry',
    name: 'Fish Thala Fry',
    price: 190,
    priceDisplay: '₹190',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Spiced and crispy deep-fried fish head, an authentic coastal delicacy bursting with flavors',
    spicyLevel: 2,
  },
  {
    id: 'spec-prawns-65',
    name: 'Prawns 65',
    price: 240,
    priceDisplay: '₹240',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'seafood',
    description: 'Golden spiced crispy prawns tossed with red chili, ginger-garlic and fried curry leaves',
    isPopular: true,
    spicyLevel: 2,
  },
  {
    id: 'spec-paal-porotta',
    name: 'Paal Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'veg',
    description: 'Flaky shredded Malabar porottas soaked in rich, aromatic cardamom-infused sweetened coconut milk',
    isChefSpecial: true,
    isPopular: true,
    spicyLevel: 0,
  },
  {
    id: 'spec-chatti-choru',
    name: 'Chatti Choru',
    price: 220,
    priceDisplay: '₹220',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'non-veg',
    description: 'Served in an earthen clay pot: hot Kerala matta rice layered with chicken/fish fry, curries, thoran, moru and chammanthi',
    isChefSpecial: true,
    isPopular: true,
    spicyLevel: 2,
  },
  {
    id: 'spec-pot-biriyani',
    name: 'Pot Biriyani',
    price: 230,
    priceDisplay: '₹230',
    category: 'SPOONS SPECIAL KERALA ITEMS',
    page: 'specials',
    diet: 'non-veg',
    description: 'Clay-pot dum cooked Malabar biriyani with fragrant kaima rice, tender spices, boiled egg and roasted cashews',
    isChefSpecial: true,
    isPopular: true,
    spicyLevel: 1,
  },

  // ==========================================
  // LUNCH (Page: specials)
  // ==========================================
  {
    id: 'lunch-veg-meal',
    name: 'Veg Meal',
    price: 90,
    priceDisplay: '₹90',
    category: 'LUNCH',
    page: 'specials',
    diet: 'veg',
    description: 'Kerala Matta / White Rice served with Sambar, Moru Curry, Parippu, Thoran, Achar & Pappadam',
  },
  {
    id: 'lunch-veg-pothichoru',
    name: 'Veg Pothichoru',
    price: 110,
    priceDisplay: '₹110',
    category: 'LUNCH',
    page: 'specials',
    diet: 'veg',
    description: 'Banana leaf wrapped parcel of rice, avial, thoran, thenga chammanthi, mezhukkupuratti & pickle',
    isPopular: true,
  },
  {
    id: 'lunch-fish-meals',
    name: 'Fish Meals',
    price: 100,
    priceDisplay: '₹100',
    category: 'LUNCH',
    page: 'specials',
    diet: 'seafood',
    description: 'Full Kerala meal accompanied by authentic spiced Fish Curry gravy, thoran and side condiments',
    isPopular: true,
  },
  {
    id: 'lunch-kerala-pothichoru',
    name: 'Kerala Pothichoru',
    price: 120,
    priceDisplay: '₹120',
    category: 'LUNCH',
    page: 'specials',
    diet: 'non-veg',
    description: 'Steamed in wilted banana leaf with fish gravy, egg roast, thoran, chammanthi and dry roast condiments',
    isPopular: true,
  },
  {
    id: 'lunch-traditional-pothichoru',
    name: 'Traditional Pothichoru',
    price: 150,
    priceDisplay: '₹150',
    category: 'LUNCH',
    page: 'specials',
    diet: 'non-veg',
    description: 'The nostalgic village experience: hot rice, fish fry, boiled egg, coconut chammanthi and homemade pickle',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'lunch-omelette-pothichoru',
    name: 'Omelette Pothichoru',
    price: 130,
    priceDisplay: '₹130',
    category: 'LUNCH',
    page: 'specials',
    diet: 'egg',
    description: 'Banana leaf wrap packed with rice, hot fluffy spiced omelette, thoran, moru and chammanthi',
  },
  {
    id: 'lunch-chicken-pothichoru',
    name: 'Chicken Pothichoru',
    price: 200,
    priceDisplay: '₹200',
    category: 'LUNCH',
    page: 'specials',
    diet: 'non-veg',
    description: 'Wholesome banana leaf meal loaded with Kerala spiced Chicken Roast, boiled egg and authentic sides',
    isPopular: true,
  },
  {
    id: 'lunch-beef-pothichoru',
    name: 'Beef Pothichoru',
    price: 220,
    priceDisplay: '₹220',
    category: 'LUNCH',
    page: 'specials',
    diet: 'non-veg',
    description: 'Signature Kerala favorite: tender Beef Ularthiyathu roast packed with rice, egg, and roasted coconut chutney',
    isPopular: true,
  },
  {
    id: 'lunch-non-veg-pothichoru',
    name: 'Non Veg Pothichoru',
    price: 250,
    priceDisplay: '₹250',
    category: 'LUNCH',
    page: 'specials',
    diet: 'non-veg',
    description: 'Grand non-veg combination feast wrapped in scorched banana leaf with chicken, beef, fish fry and accompaniments',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // KAPPA (Page: specials)
  // ==========================================
  {
    id: 'kappa-plain',
    name: 'Kappa',
    price: 50,
    priceDisplay: '₹50',
    category: 'KAPPA',
    page: 'specials',
    diet: 'veg',
    description: 'Boiled and seasoned tapioca mashed with turmeric, crushed green chilies and tempered curry leaves',
  },
  {
    id: 'kappa-beef',
    name: 'Kappa Beef',
    price: 150,
    priceDisplay: '₹150',
    category: 'KAPPA',
    page: 'specials',
    diet: 'non-veg',
    description: 'The legendary "Kappa Biriyani / Ellum Kappayum": seasoned tapioca blended with spicy roasted beef chunks',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kappa-chicken',
    name: 'Kappa Chicken',
    price: 140,
    priceDisplay: '₹140',
    category: 'KAPPA',
    page: 'specials',
    diet: 'non-veg',
    description: 'Mashed seasoned tapioca tossed in a rich, slow-cooked Kerala chicken masala with coconut oil',
  },
  {
    id: 'kappa-fish-curry',
    name: 'Kappa Fish Curry',
    price: 130,
    priceDisplay: '₹130',
    category: 'KAPPA',
    page: 'specials',
    diet: 'seafood',
    description: 'Piping hot boiled kappa served alongside spicy and tangy kudampuli fish curry',
    isPopular: true,
  },
  {
    id: 'kappa-fish-fry',
    name: 'Kappa Fish Fry',
    price: 130,
    priceDisplay: '₹130',
    category: 'KAPPA',
    page: 'specials',
    diet: 'seafood',
    description: 'Traditional seasoned kappa served with crispy pan-fried Kerala fish slice and onion chutney',
  },

  // ==========================================
  // PUTTU ITEMS (Page: specials)
  // ==========================================
  {
    id: 'puttu-egg',
    name: 'Egg Puttu',
    price: 130,
    priceDisplay: '₹130',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'egg',
    description: 'Cylindrical steamed rice cake layered with freshly grated coconut and spiced egg masala',
  },
  {
    id: 'puttu-beef',
    name: 'Beef Puttu',
    price: 150,
    priceDisplay: '₹150',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'non-veg',
    description: 'Steamed puttu layered with caramelized onion and slow-roasted Kerala beef cubes',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'puttu-chicken',
    name: 'Chicken Puttu',
    price: 140,
    priceDisplay: '₹140',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'non-veg',
    description: 'Steamed puttu cylinders layered with savory country-style spiced chicken roast',
    isPopular: true,
  },
  {
    id: 'puttu-kadala',
    name: 'Kadala Puttu',
    price: 120,
    priceDisplay: '₹120',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'veg',
    description: 'Classic Kerala comfort combination of steamed puttu served with roasted black chickpea curry',
  },
  {
    id: 'puttu-green-peas',
    name: 'Green Peas Puttu',
    price: 120,
    priceDisplay: '₹120',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'veg',
    description: 'Steamed puttu paired with aromatic spiced green peas and coconut milk curry',
  },
  {
    id: 'puttu-nonveg-mixed',
    name: 'Non Veg Mixed Puttu',
    price: 200,
    priceDisplay: '₹200',
    category: 'PUTTU ITEMS',
    page: 'specials',
    diet: 'non-veg',
    description: 'Chef special layered puttu with succulent beef, chicken and egg roast fillings',
    isChefSpecial: true,
  },

  // ==========================================
  // KERALA VARIETY (Page: specials)
  // ==========================================
  {
    id: 'var-appam',
    name: 'Appam',
    price: 20,
    priceDisplay: '₹20',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Fermented rice and coconut hoppers with crisp lace edges and soft fluffy center',
  },
  {
    id: 'var-puttu',
    name: 'Puttu',
    price: 50,
    priceDisplay: '₹50',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Traditional steamed rice flour and grated coconut cylinders',
  },
  {
    id: 'var-chappathi',
    name: 'Chappathi',
    price: 20,
    priceDisplay: '₹20',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Soft whole wheat flatbread made fresh on the tawa',
  },
  {
    id: 'var-porotta',
    name: 'Porotta',
    price: 25,
    priceDisplay: '₹25',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Crisp, multi-layered flaky Malabar flatbread made with seasoned dough',
    isPopular: true,
  },
  {
    id: 'var-kuboos',
    name: 'Kuboos',
    price: 15,
    priceDisplay: '₹15',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Oven-baked Arabic pita flatbread, great with grills and curries',
  },
  {
    id: 'var-pazham-pori',
    name: 'Pazham Pori',
    price: 15,
    priceDisplay: '₹15',
    category: 'KERALA VARIETY',
    page: 'specials',
    diet: 'veg',
    description: 'Crisp golden batter-fried ripe Nendran banana fritters',
    isPopular: true,
  },

  // ==========================================
  // KIZHI BIRIYANI (Page: biriyani)
  // ==========================================
  {
    id: 'kizhi-plain',
    name: 'Plain Kizhi Biriyani',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Fragrant Malabar kaima rice wrapped in banana leaf and steam-roasted to infuse banana-leaf aroma',
  },
  {
    id: 'kizhi-paneer',
    name: 'Paneer Kizhi Biriyani',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Tender cottage cheese cubes tossed in spicy Kerala masala, sealed in banana leaf with biriyani rice',
  },
  {
    id: 'kizhi-mushroom',
    name: 'Mushroom Kizhi Biriyani',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Button mushrooms sauteed in shallot pepper masala, bundled and steamed inside scorched plantain leaf',
  },
  {
    id: 'kizhi-gobi',
    name: 'Gobi Kizhi Biriyani',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Cauliflower florets spiced and layered with rich kaima biriyani in a tied banana pouch',
  },
  {
    id: 'kizhi-egg',
    name: 'Egg Kizhi Biriyani',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'egg',
    description: 'Hard-boiled eggs coated in thick spicy gravy, steamed inside banana leaf with ghee-infused rice',
  },
  {
    id: 'kizhi-chicken',
    name: 'Chicken Kizhi Biriyani',
    price: 180,
    priceDisplay: '₹180',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Signature Malabar chicken biriyani parcel tied in scorched banana leaf and tawa-steamed to perfection',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kizhi-beef',
    name: 'Beef Kizhi Biriyani',
    price: 190,
    priceDisplay: '₹190',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Succulent slow-cooked beef masala layered with spiced rice, sealed and roasted in plantain leaves',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kizhi-65',
    name: '65 Kizhi Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Crispy spicy Chicken 65 chunks bundled with flavorful biriyani rice in banana leaf',
    isPopular: true,
  },
  {
    id: 'kizhi-nonveg-special',
    name: 'Non Veg Special Kizhi Biriyani',
    price: 220,
    priceDisplay: '₹220',
    category: 'KIZHI BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Grand royal assortment of chicken, beef and egg in fragrant leaf-wrapped steam biriyani',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // BIRIYANI (Page: biriyani)
  // ==========================================
  {
    id: 'bir-ghee-rice',
    name: 'Ghee Rice',
    price: 100,
    priceDisplay: '₹100',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Classic Neychoru made with Jeerakasala rice, whole spices, pure ghee and golden fried onions',
    isPopular: true,
  },
  {
    id: 'bir-chicken-110',
    name: 'Chicken Biriyani',
    price: 110,
    priceDisplay: '₹110',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Authentic Thalassery style dum biriyani with aromatic short-grain rice and spiced tender chicken',
  },
  {
    id: 'bir-paneer',
    name: 'Paneer Biriyani',
    price: 130,
    priceDisplay: '₹130',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Rich cottage cheese cubes layered with caramelized shallots and fragrant saffron biriyani rice',
  },
  {
    id: 'bir-mushroom',
    name: 'Mushroom Biriyani',
    price: 130,
    priceDisplay: '₹130',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Earthy button mushrooms slow-cooked with Malabar spices and layered over dum rice',
  },
  {
    id: 'bir-gobi',
    name: 'Gobi Biriyani',
    price: 130,
    priceDisplay: '₹130',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'veg',
    description: 'Spiced cauliflower cooked with mint, coriander, fried onions and fragrant rice',
  },
  {
    id: 'bir-chicken-140',
    name: 'Chicken Biriyani (Dum Special)',
    price: 140,
    priceDisplay: '₹140',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Double portion dum chicken biriyani slow cooked with cashews, raisins and raita',
    isPopular: true,
  },
  {
    id: 'bir-beef',
    name: 'Beef Biriyani',
    price: 150,
    priceDisplay: '₹150',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Tender succulent beef cuts marinated with fennel, star anise and slow simmered in biriyani dum',
    isPopular: true,
  },
  {
    id: 'bir-65',
    name: '65 Biriyani',
    price: 170,
    priceDisplay: '₹170',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Aromatic biriyani rice topped with hot crisp Chicken 65 pieces, onions and lemon',
  },
  {
    id: 'bir-special-chicken',
    name: 'Special Chicken Biriyani',
    price: 170,
    priceDisplay: '₹170',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Extra tender pieces of marinated chicken with boiled egg and spiced masala reduction',
    isPopular: true,
  },
  {
    id: 'bir-special-beef',
    name: 'Special Beef Biriyani',
    price: 180,
    priceDisplay: '₹180',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Rich spiced Kerala beef chunks with fried dry-fruits, egg and thick biriyani gravy',
    isChefSpecial: true,
  },
  {
    id: 'bir-al-faham',
    name: 'Al Faham Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Smoky charcoal-grilled Arabian Al Faham chicken paired with seasoned biriyani rice and garlic mayo',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // SPOONS SPECIAL BUTTER BIRIYANI (Page: biriyani)
  // ==========================================
  {
    id: 'butter-chick-bir',
    name: 'Butter Chicken Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Rich creamy makhani spiced chicken tossed with fragrant biriyani rice and white butter',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'butter-beef-bir',
    name: 'Butter Beef Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Kerala beef braised in aromatic spices finished in velvety butter gravy and dum rice',
  },
  {
    id: 'kadai-chick-bir',
    name: 'Kadai Chicken Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Wok-tossed chicken with crushed coriander seeds, bell peppers and richly spiced rice',
  },
  {
    id: 'kadai-beef-bir',
    name: 'Kadai Beef Biriyani',
    price: 200,
    priceDisplay: '₹200',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Kadai spiced slow-cooked beef with capsicum, onion flakes and fragrant biriyani rice',
  },
  {
    id: 'mix-butter-bir',
    name: 'Mix Butter Biriyani',
    price: 250,
    priceDisplay: '₹250',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Chef combination of chicken and beef tossed in buttery rich makhani gravy with aromatic rice',
    isChefSpecial: true,
  },
  {
    id: 'mix-kadai-bir',
    name: 'Mix Kadai Biriyani',
    price: 250,
    priceDisplay: '₹250',
    category: 'SPOONS SPECIAL BUTTER BIRIYANI',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Spicy wok tossed mixture of chicken, beef and egg in authentic kadai spices and ghee rice',
    isChefSpecial: true,
  },

  // ==========================================
  // KIZHI POROTTA (Page: biriyani)
  // ==========================================
  {
    id: 'kp-gobi',
    name: 'Gobi Kizhi Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Flaky Malabar porottas layered with spiced cauliflower roast and steam-cooked in plantain leaf',
  },
  {
    id: 'kp-paneer',
    name: 'Paneer Kizhi Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Soft paneer chunks in rich coconut gravy wrapped between porottas and roasted in leaf pouch',
  },
  {
    id: 'kp-mushroom',
    name: 'Mushroom Kizhi Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Earthy mushroom masala infused between layers of Malabar porotta in smoked banana leaf',
  },
  {
    id: 'kp-kadala',
    name: 'Kadala Kizhi Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Black chickpeas cooked in roasted coconut gravy soaked between steaming hot porottas',
  },
  {
    id: 'kp-green-peas',
    name: 'Green Peas Kizhi Porotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Spiced green peas masala and soft flaky porotta parcel steamed to absorb plantain sweetness',
  },
  {
    id: 'kp-egg',
    name: 'Egg Kizhi Porotta',
    price: 130,
    priceDisplay: '₹130',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'egg',
    description: 'Boiled egg and spicy onion-tomato masala sealed between two Malabar porottas in banana leaf',
  },
  {
    id: 'kp-chicken',
    name: 'Chicken Kizhi Porotta',
    price: 140,
    priceDisplay: '₹140',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Kerala restaurant legend: juicy chicken curry gravy soaked deep into layered porotta inside tied leaf',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kp-beef',
    name: 'Beef Kizhi Porotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Tender beef roast with caramelized coconut pieces sandwiched in porotta and steam-charred in leaf',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kp-spec-gobi',
    name: 'Special Gobi Kizhi Porotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Extra portion spiced gobi with cashews and thick Kerala kurma gravy inside porotta',
  },
  {
    id: 'kp-spec-paneer',
    name: 'Special Paneer Kizhi Porotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Premium paneer cubes in buttery spiced onion masala wrapped in layered porotta',
  },
  {
    id: 'kp-spec-mushroom',
    name: 'Special Mushroom Kizhi Porotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Special portion mushroom pepper masala layered between golden parottas',
  },
  {
    id: 'kp-spec-kadala-gobi',
    name: 'Special Kadala Gobi Kizhi Porotta',
    price: 170,
    priceDisplay: '₹170',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Delightful pairing of spiced chickpeas and cauliflower florets steamed inside leaf-wrapped porottas',
  },
  {
    id: 'kp-spec-greenpeas-gobi',
    name: 'Special Green Peas Gobi Porotta',
    price: 170,
    priceDisplay: '₹170',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Green peas and gobi cooked in thick coconut paste enveloped with layered flaky parottas',
  },
  {
    id: 'kp-spec-egg',
    name: 'Special Egg Kizhi Porotta',
    price: 170,
    priceDisplay: '₹170',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'egg',
    description: 'Double egg roast preparation with rich shallot gravy and steam-softened porottas',
  },
  {
    id: 'kp-spec-chicken',
    name: 'Special Chicken Kizhi Porotta',
    price: 190,
    priceDisplay: '₹190',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Chef signature with generous chicken roast, boiled egg and aromatic spice gravy in banana leaf',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kp-spec-beef',
    name: 'Special Beef Kizhi Porotta',
    price: 200,
    priceDisplay: '₹200',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Double beef roast preparation with extra curry and roasted coconut bits inside charred banana leaf',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kp-nonveg-spec-mixed',
    name: 'Non Veg Special Mixed Kizhi Porotta',
    price: 250,
    priceDisplay: '₹250',
    category: 'KIZHI POROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'The ultimate royal feast: chicken roast, beef roast and egg combined within multiple porotta layers',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // KOTTHU PAROTTA (Page: biriyani)
  // ==========================================
  {
    id: 'kothu-gobi',
    name: 'Gobi Kothu Parotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Shredded porotta chopped vigorously on hot iron tawa with cauliflower, onions and curry leaves',
  },
  {
    id: 'kothu-paneer',
    name: 'Paneer Kothu Parotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Chopped flaky porottas tossed on the griddle with paneer cubes and freshly ground spices',
  },
  {
    id: 'kothu-mushroom',
    name: 'Mushroom Kothu Parotta',
    price: 120,
    priceDisplay: '₹120',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Fresh mushrooms sliced and stir-fried with shredded porotta, green chilies and spices',
  },
  {
    id: 'kothu-egg',
    name: 'Egg Kothu Parotta',
    price: 130,
    priceDisplay: '₹130',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'egg',
    description: 'Fluffy scrambled eggs and chopped porotta beaten together on the tawa with aromatic salna',
    isPopular: true,
  },
  {
    id: 'kothu-chicken',
    name: 'Chicken Kothu Parotta',
    price: 140,
    priceDisplay: '₹140',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Tawa-chopped porotta with shredded tender chicken, egg, spicy salna gravy and cilantro',
    isPopular: true,
  },
  {
    id: 'kothu-beef',
    name: 'Beef Kothu Parotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Spicy chopped porotta combined with flavorful roasted beef bits, eggs and black pepper',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'kothu-spec-gobi',
    name: 'Special Gobi Kothu Parotta',
    price: 140,
    priceDisplay: '₹140',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Extra portion of crispy spiced gobi blended with minced porotta and roasted curry leaves',
  },
  {
    id: 'kothu-spec-paneer',
    name: 'Special Paneer Kothu Parotta',
    price: 140,
    priceDisplay: '₹140',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Special edition with soft paneer cubes, capsicum and spicy salna gravy on tawa',
  },
  {
    id: 'kothu-spec-mushroom',
    name: 'Special Mushroom Kothu Parotta',
    price: 140,
    priceDisplay: '₹140',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'veg',
    description: 'Double mushroom sauteed with peppery spices and shredded flaky Malabar porottas',
  },
  {
    id: 'kothu-spec-egg',
    name: 'Special Egg Kothu Parotta',
    price: 150,
    priceDisplay: '₹150',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'egg',
    description: 'Three farm eggs beaten into minced porottas with extra spices, onions and curry leaves',
  },
  {
    id: 'kothu-spec-chicken',
    name: 'Special Chicken Kothu Parotta',
    price: 160,
    priceDisplay: '₹160',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Generous portions of spiced chicken meat, double egg and rich aromatic Kerala salna gravy',
    isPopular: true,
  },
  {
    id: 'kothu-spec-beef',
    name: 'Special Beef Kothu Parotta',
    price: 170,
    priceDisplay: '₹170',
    category: 'KOTTHU PAROTTA',
    page: 'biriyani',
    diet: 'non-veg',
    description: 'Special roasted beef chunks vigorously chopped with parottas, eggs and Tellicherry black pepper',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // CHICKEN ITEMS (Page: mains)
  // ==========================================
  {
    id: 'chk-65',
    name: 'Chicken 65',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Crispy deep-fried chicken morsels marinated in red chili paste, ginger, garlic and curry leaves',
    isPopular: true,
  },
  {
    id: 'chk-chilly',
    name: 'Chilly Chicken',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Indo-Chinese style tender chicken tossed with bell peppers, green chilies and savory soy sauce',
  },
  {
    id: 'chk-roast',
    name: 'Chicken Roast',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Traditional Kerala semi-dry chicken roast made with slow-caramelized shallots and crushed spices',
    isPopular: true,
  },
  {
    id: 'chk-kadai',
    name: 'Chicken Kadai',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Chicken cooked in iron kadai with freshly ground coriander seeds, dry red chilies and bell peppers',
  },
  {
    id: 'chk-ularthiyathu',
    name: 'Chicken Ularthiyathu',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Authentic Kerala style dry pan-roasted chicken with sliced coconut flakes and curry leaves',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'chk-pepper',
    name: 'Pepper Chicken',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Spicy chicken fry tossed with crushed black peppercorns, onions, garlic and coconut oil',
  },
  {
    id: 'chk-varutharachathu',
    name: 'Chicken Varutharachathu',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'A classic heritage recipe with fresh grated coconut roasted to deep brown and ground into velvety gravy',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'chk-mulakittathu',
    name: 'Chicken Mulakittathu',
    price: 200,
    priceDisplay: '₹200',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Fiery red chicken curry cooked with red chilies, shallots and hints of vinegar and tamarind',
  },
  {
    id: 'chk-butter',
    name: 'Butter Chicken',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Tender chicken pieces simmered in silky tomato, butter, cashew and cream makhani sauce',
  },
  {
    id: 'chk-chettinadu',
    name: 'Chicken Chettinadu',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Aromatic spicy curry infused with stone flower (kalpasi), star anise, pepper and roasted spices',
  },
  {
    id: 'chk-porichathu',
    name: 'Chicken Porichathu',
    price: 150,
    priceDisplay: '₹150',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Malabar style golden deep-fried chicken marinated in red chili, garlic and coconut oil',
    isPopular: true,
  },
  {
    id: 'chk-garlic',
    name: 'Garlic Chicken',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Juicy chicken tossed with heaps of aromatic browned garlic, green chilies and savory sauce',
  },
  {
    id: 'chk-manchurian',
    name: 'Chicken Manchurian',
    price: 220,
    priceDisplay: '₹220',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Crispy batter chicken pieces tossed in tangy Indo-Chinese Manchurian glaze with spring onions',
  },
  {
    id: 'chk-spoons-special-curry',
    name: 'Spoons Special Chicken Curry',
    price: 250,
    priceDisplay: '₹250',
    category: 'CHICKEN ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'House secret recipe: country chicken simmered in rich spiced coconut cream with freshly crushed whole spices',
    isChefSpecial: true,
    isPopular: true,
  },

  // ==========================================
  // BEEF ITEMS (Page: mains)
  // ==========================================
  {
    id: 'beef-pepper-masala',
    name: 'Pepper Beef Masala',
    price: 220,
    priceDisplay: '₹220',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Tender beef cubes tossed with crushed Tellicherry black pepper, shallots and curry leaves',
    isPopular: true,
  },
  {
    id: 'beef-kadai',
    name: 'Beef Kadai',
    price: 220,
    priceDisplay: '₹220',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Spiced beef slow-braised in a traditional iron kadai with crisp onions and green capsicum',
  },
  {
    id: 'beef-chettinadu',
    name: 'Beef Chettinadu',
    price: 220,
    priceDisplay: '₹220',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'South Indian dry-roasted spice blend with star anise, fennel and poppy seed gravy',
  },
  {
    id: 'beef-butter-masala',
    name: 'Beef Butter Masala',
    price: 220,
    priceDisplay: '₹220',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'A rich and creamy fusion of tender spiced beef cooked in velvety butter and tomato reduction',
  },
  {
    id: 'beef-roast',
    name: 'Beef Roast',
    price: 180,
    priceDisplay: '₹180',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'The world-famous Kerala Beef Roast: slow-cooked meat with caramelized shallots, ginger and aromatic spices',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'beef-ularthiyathu',
    name: 'Beef Ularthiyathu',
    price: 180,
    priceDisplay: '₹180',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Dry roasted beef fry with golden coconut slices (thengakothu) and aromatic curry leaves in coconut oil',
    isChefSpecial: true,
    isPopular: true,
  },
  {
    id: 'beef-curry',
    name: 'Beef Curry',
    price: 180,
    priceDisplay: '₹180',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Homestyle Kerala beef curry with a fragrant onion, tomato, coriander and coconut gravy',
    isPopular: true,
  },
  {
    id: 'beef-chilly',
    name: 'Beef Chilly',
    price: 200,
    priceDisplay: '₹200',
    category: 'BEEF ITEMS',
    page: 'mains',
    diet: 'non-veg',
    description: 'Crisp spicy beef strips wok-tossed with capsicum, slit green chilies and dark savory seasoning',
    isPopular: true,
  },

  // ==========================================
  // EGG ITEMS (Page: mains)
  // ==========================================
  {
    id: 'egg-roast',
    name: 'Egg Roast',
    price: 60,
    priceDisplay: '₹60',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Hard-boiled eggs coated in thick, slow-caramelized spicy onion and tomato masala with curry leaves',
    isPopular: true,
  },
  {
    id: 'egg-burji',
    name: 'Egg Burji',
    price: 50,
    priceDisplay: '₹50',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Indian spiced scrambled eggs tossed with finely chopped onions, tomatoes, ginger and green chillies',
  },
  {
    id: 'egg-omelette',
    name: 'Egg Omelette',
    price: 20,
    priceDisplay: '₹20',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Classic double-egg omelette beaten with onions, green chilies and cracked black pepper',
  },
  {
    id: 'egg-half-boil',
    name: 'Half Boil',
    price: 20,
    priceDisplay: '₹20',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Pan-fried sunny side egg with runny yolk, seasoned with black pepper and sea salt',
  },
  {
    id: 'egg-one-side-omelette',
    name: 'One Side Omelette',
    price: 20,
    priceDisplay: '₹20',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Fluffy single-side seared omelette seasoned with pepper and curry leaves',
  },
  {
    id: 'egg-boiled',
    name: 'Boiled Egg',
    price: 15,
    priceDisplay: '₹15',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Fresh farm egg boiled to perfection, served whole with salt and pepper',
  },
  {
    id: 'egg-spoons-special-masala',
    name: 'Spoons Special Egg Masala',
    price: 150,
    priceDisplay: '₹150',
    category: 'EGG ITEMS',
    page: 'mains',
    diet: 'egg',
    description: 'Chef specialty with whole fried eggs in rich cashew coconut gravy with shallots and whole spices',
    isChefSpecial: true,
  },

  // ==========================================
  // VEG CURRY (Page: mains)
  // ==========================================
  {
    id: 'veg-kadala-curry',
    name: 'Kadala Curry',
    price: 60,
    priceDisplay: '₹60',
    category: 'VEG CURRY',
    page: 'mains',
    diet: 'veg',
    description: 'Traditional black chickpea curry in roasted coconut gravy tempered with mustard seeds and curry leaves',
    isPopular: true,
  },
  {
    id: 'veg-green-peas-curry',
    name: 'Green Peas Curry',
    price: 60,
    priceDisplay: '₹60',
    category: 'VEG CURRY',
    page: 'mains',
    diet: 'veg',
    description: 'Tender green peas simmered in a mildly spiced coconut milk and onion gravy',
  },
  {
    id: 'veg-paneer-masala',
    name: 'Paneer Masala',
    price: 100,
    priceDisplay: '₹100',
    category: 'VEG CURRY',
    page: 'mains',
    diet: 'veg',
    description: 'Fresh paneer cubes cooked in a savory, aromatic onion-tomato curry with garam masala',
  },
  {
    id: 'veg-mushroom-masala',
    name: 'Mushroom Masala',
    price: 100,
    priceDisplay: '₹100',
    category: 'VEG CURRY',
    page: 'mains',
    diet: 'veg',
    description: 'Plump button mushrooms stewed in a fragrant South Indian spiced tomato gravy',
  },
  {
    id: 'veg-gobi-masala',
    name: 'Gobi Masala',
    price: 100,
    priceDisplay: '₹100',
    category: 'VEG CURRY',
    page: 'mains',
    diet: 'veg',
    description: 'Cauliflower florets cooked with shallots, cumin, coriander and fresh herbs',
  },

  // ==========================================
  // FRIED RICE (Page: rice-noodles)
  // ==========================================
  {
    id: 'rice-veg',
    name: 'Veg Rice',
    price: 110,
    priceDisplay: '₹110',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Fragrant basmati rice stir-fried in a hot wok with finely chopped carrots, beans and spring onions',
  },
  {
    id: 'rice-gobi',
    name: 'Gobi Rice',
    price: 120,
    priceDisplay: '₹120',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Crisp seasoned cauliflower florets tossed with aromatic fried rice and herbs',
  },
  {
    id: 'rice-mushroom',
    name: 'Mushroom Rice',
    price: 120,
    priceDisplay: '₹120',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Wok-tossed basmati rice with sliced button mushrooms, garlic and white pepper',
  },
  {
    id: 'rice-paneer',
    name: 'Paneer Rice',
    price: 120,
    priceDisplay: '₹120',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Golden paneer cubes tossed into fluffy seasoned fried rice with scallions',
  },
  {
    id: 'rice-egg',
    name: 'Egg Rice',
    price: 130,
    priceDisplay: '₹130',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'egg',
    description: 'Scrambled eggs wok-tossed with fragrant basmati grains, onions and soya seasoning',
    isPopular: true,
  },
  {
    id: 'rice-chicken',
    name: 'Chicken Rice',
    price: 140,
    priceDisplay: '₹140',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Tender diced chicken breast stir-fried with egg, vegetables and fragrant long-grain rice',
    isPopular: true,
  },
  {
    id: 'rice-beef',
    name: 'Beef Rice',
    price: 150,
    priceDisplay: '₹150',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Savory fried rice with spiced tender beef morsels, green chilies and dark seasoning',
    isPopular: true,
  },
  {
    id: 'rice-mixed',
    name: 'Mixed Rice',
    price: 220,
    priceDisplay: '₹220',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Grand wok combination of chicken, beef, egg and garden fresh vegetables',
    isChefSpecial: true,
  },
  {
    id: 'rice-sch-veg',
    name: 'Schezwan Veg Rice',
    price: 120,
    priceDisplay: '₹120',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Spicy wok fried rice tossed in fiery home-made Schezwan chili garlic sauce',
  },
  {
    id: 'rice-sch-gobi',
    name: 'Schezwan Gobi Rice',
    price: 130,
    priceDisplay: '₹130',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Crisp gobi tossed with Schezwan peppers, red chili paste and seasoned rice',
  },
  {
    id: 'rice-sch-paneer',
    name: 'Schezwan Paneer Rice',
    price: 130,
    priceDisplay: '₹130',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Soft cottage cheese cubes infused with spicy Schezwan oil and fried rice',
  },
  {
    id: 'rice-sch-mushroom',
    name: 'Schezwan Mushroom Rice',
    price: 130,
    priceDisplay: '₹130',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Fresh mushrooms in hot Schezwan wok sauce tossed with aromatic basmati rice',
  },
  {
    id: 'rice-sch-egg',
    name: 'Schezwan Egg Rice',
    price: 140,
    priceDisplay: '₹140',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'egg',
    description: 'Scrambled eggs wok-tossed with red chili garlic Schezwan blend and spring onion',
  },
  {
    id: 'rice-sch-chicken',
    name: 'Schezwan Chicken Rice',
    price: 150,
    priceDisplay: '₹150',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Juicy chicken chunks and fluffy rice stir-fried in signature spicy Schezwan sauce',
    isPopular: true,
  },
  {
    id: 'rice-sch-beef',
    name: 'Schezwan Beef Rice',
    price: 160,
    priceDisplay: '₹160',
    category: 'FRIED RICE',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Spiced tender beef morsels tossed with fiery Schezwan paste, peppers and rice',
    isPopular: true,
  },

  // ==========================================
  // NOODLES (Page: rice-noodles)
  // ==========================================
  {
    id: 'nood-veg',
    name: 'Veg Noodles',
    price: 120,
    priceDisplay: '₹120',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Soft noodles tossed with julienned vegetables, cabbage, carrots and light soya sauce',
  },
  {
    id: 'nood-gobi',
    name: 'Gobi Noodles',
    price: 140,
    priceDisplay: '₹140',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Wok tossed noodles loaded with crisp golden cauliflower bites and scallions',
  },
  {
    id: 'nood-mushroom',
    name: 'Mushroom Noodles',
    price: 140,
    priceDisplay: '₹140',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Earthy button mushrooms stir-fried with hakka noodles and white pepper',
  },
  {
    id: 'nood-paneer',
    name: 'Paneer Noodles',
    price: 140,
    priceDisplay: '₹140',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Soft paneer cubes tossed into wok-seared noodles with crisp capsicum',
  },
  {
    id: 'nood-egg',
    name: 'Egg Noodles',
    price: 140,
    priceDisplay: '₹140',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'egg',
    description: 'Scrambled eggs and vegetables tossed with long noodles in light Asian sauce',
  },
  {
    id: 'nood-chicken',
    name: 'Chicken Noodles',
    price: 150,
    priceDisplay: '₹150',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Shredded chicken and egg stir-fried with savory noodles on high wok flame',
    isPopular: true,
  },
  {
    id: 'nood-beef',
    name: 'Beef Noodles',
    price: 160,
    priceDisplay: '₹160',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Marinated beef strips stir-fried with egg, green peppers and noodles in savory sauce',
    isPopular: true,
  },
  {
    id: 'nood-mixed',
    name: 'Mixed Noodles',
    price: 200,
    priceDisplay: '₹200',
    category: 'NOODLES',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Deluxe noodle bowl with chicken, beef, egg and fresh crunchy vegetables',
    isChefSpecial: true,
  },

  // ==========================================
  // ROLL ITEMS (Page: rice-noodles)
  // ==========================================
  {
    id: 'roll-veg',
    name: 'Veg Rolls',
    price: 60,
    priceDisplay: '₹60',
    category: 'ROLL ITEMS',
    page: 'rice-noodles',
    diet: 'veg',
    description: 'Crispy warm parotta wrap stuffed with seasoned mixed vegetables and house mint chutney',
  },
  {
    id: 'roll-egg',
    name: 'Egg Rolls',
    price: 70,
    priceDisplay: '₹70',
    category: 'ROLL ITEMS',
    page: 'rice-noodles',
    diet: 'egg',
    description: 'Tawa-toasted parotta layered with egg, sliced crunchy onions, green chilies and sauce',
    isPopular: true,
  },
  {
    id: 'roll-chicken',
    name: 'Chicken Rolls',
    price: 80,
    priceDisplay: '₹80',
    category: 'ROLL ITEMS',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Spicy shredded chicken roast rolled in a hot flaky Malabar parotta with tangy onions',
    isPopular: true,
  },
  {
    id: 'roll-beef',
    name: 'Beef Rolls',
    price: 90,
    priceDisplay: '₹90',
    category: 'ROLL ITEMS',
    page: 'rice-noodles',
    diet: 'non-veg',
    description: 'Succulent roasted Kerala beef cubes with black pepper and onions in crisp parotta wrap',
    isChefSpecial: true,
    isPopular: true,
  },
];

// Group items by category for each page
export function getCategoriesByPage(page: 'specials' | 'biriyani' | 'mains' | 'rice-noodles'): MenuCategory[] {
  const pageItems = MENU_ITEMS.filter((item) => item.page === page);
  const categoriesInPage = Array.from(new Set(pageItems.map((item) => item.category)));

  return categoriesInPage.map((catName) => {
    return {
      id: catName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      title: catName,
      page,
      items: pageItems.filter((i) => i.category === catName),
    };
  });
}
